#!/bin/bash

sudo rm -rf build dist &> /dev/null
sudo find . -name \*.pyc -delete

# update version info
bin/gitver update version
sudo python2 setup.py develop
sudo rm -rf build dist &> /dev/null
sudo find . -name \*.pyc -delete
