#!/bin/bash

if [ "`whoami`" == "root" ]; then
    echo "Do not run this script with root privileges, your credentials will be asked     when needed."
    exit
fi

sudo rm -rf build dist &> /dev/null
sudo find . -name \*.pyc -delete

# update version info
bin/gitver update version
sudo python2 setup.py develop
sudo rm -rf build dist &> /dev/null
sudo find . -name \*.pyc -delete
