#!/bin/bash
rm gitver/_version.py gitver/_version.pyc gitver/version.py gitver/version.pyc &> /dev/null
bin/gitver update release
sudo rm -rf build dist &> /dev/null

echo "Building release version..."
sudo python2 setup.py sdist
echo -e "\nPush it to PyPI when ready with \"python2 setup.py upload\""