#!/bin/bash

# remove additional debug version information at this point
sudo rm -rf build dist &> /dev/null
rm -f gitver/_version_next.py
sudo find . -name \*.pyc -delete


# build release version info
bin/gitver update release

echo "Building release version..."
python2 setup.py sdist
echo -e "\nPush it to PyPI when ready with \"python2 setup.py sdist upload\""
