#!/bin/bash

if [ "`whoami`" == "root" ]; then
    echo "Do not run this script with root privileges, your credentials will be asked     when needed."
    exit
fi

# remove additional debug version information at this point
sudo rm -rf build dist &> /dev/null
sudo find . -name \*.pyc -delete

# update version info
bin/gitver update version

echo "Building release version..."
python setup.py sdist
echo -e "\nPush it to PyPI when ready with \"python setup.py sdist upload\""
